In [23]:
import pandas as py
import numpy as np

In [24]:
data = py.read_json('../data/data/raw/groundwater.jsonl',lines=True)
df = py.DataFrame(data)
print(df.head())

   _id  SlNo                         Station Agency  State LGD Code  \
0    1     1  390713- Jairampur PMS -Shallow   UPGW               9
1    2     2  390713- Jairampur PMS -Shallow   UPGW               9
2    3     3  390713- Jairampur PMS -Shallow   UPGW               9
3    4     4  390713- Jairampur PMS -Shallow   UPGW               9
4    5     5  390713- Jairampur PMS -Shallow   UPGW               9

           State  District LGD Code  District Tehsil Block  ... Basin  \
0  Uttar Pradesh                187  VARANASI      -     -  ...     -
1  Uttar Pradesh                187  VARANASI      -     -  ...     -
2  Uttar Pradesh                187  VARANASI      -     -  ...     -
3  Uttar Pradesh                187  VARANASI      -     -  ...     -
4  Uttar Pradesh                187  VARANASI      -     -  ...     -

  Tributary Subtributary SubSubtributary Local River  Latitude Longitude  \
0         -            -               -           -  25.41945     83.03
1         -            -               -           -  25.41945     83.03
2         -            -               -           -  25.41945     83.03
3         -            -               -           -  25.41945     83.03
4         -            -               -           -  25.41945     83.03

   RL_MSL  Data Acquisition Time  Groundwater Level Telemetry 6 Hourly (meter)
0     NaN       23-02-2024 18:00                                        -0.247
1     NaN       24-02-2024 00:00                                        -0.256
2     NaN       24-02-2024 06:00                                        -0.252
3     NaN       24-02-2024 12:00                                        -0.167
4     NaN       24-02-2024 18:00                                        -0.256

[5 rows x 22 columns]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336200 entries, 0 to 336199
Data columns (total 22 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   _id                                           336200 non-null  int64
 1   SlNo                                          336200 non-null  int64
 2   Station                                       336200 non-null  object
 3   Agency                                        336200 non-null  object
 4   State LGD Code                                336200 non-null  int64
 5   State                                         336200 non-null  object
 6   District LGD Code                             336200 non-null  int64
 7   District                                      336200 non-null  object
 8   Tehsil                                        336200 non-null  object
 9   Block                                         336200 non-null  object
 10  Village                                       336200 non-null  object
 11  River                                         336200 non-null  object
 12  Basin                                         336200 non-null  object
 13  Tributary                                     336200 non-null  object
 14  Subtributary                                  336200 non-null  object
 15  SubSubtributary                               336200 non-null  object
 16  Local River                                   336200 non-null  object
 17  Latitude                                      336200 non-null  float64
 18  Longitude                                     336200 non-null  float64
 19  RL_MSL                                        99476 non-null   float64
 20  Data Acquisition Time                         336200 non-null  object
 21  Groundwater Level Telemetry 6 Hourly (meter)  336200 non-null  float64
dtypes: float64(4), int64(4), object(14)
memory usage: 56.4+ MB

In [26]:
df.describe()

,_id,SlNo,State LGD Code,District LGD Code,Latitude,Longitude,RL_MSL,Groundwater Level Telemetry 6 Hourly (meter)
count,336200.000000,336200.000000,336200.0,336200.000000,336200.000000,336200.000000,99476.000000,336200.000000
mean,168100.500000,168100.500000,9.0,167.815687,26.694003,80.170261,181.886133,-5.636372
std,97052.724588,97052.724588,0.0,108.016608,1.402123,1.927520,69.454750,55.927805
min,1.000000,1.000000,9.0,118.000000,24.723333,77.395556,83.000000,-999.999000
25%,84050.750000,84050.750000,9.0,124.000000,25.661966,78.450860,120.000000,-16.071000
50%,168100.500000,168100.500000,9.0,142.000000,26.066101,80.297794,160.000000,-6.818000
75%,252150.250000,252150.250000,9.0,169.000000,28.008239,81.859608,221.000000,-1.344000
max,336200.000000,336200.000000,9.0,659.000000,29.990556,83.682103,335.000000,1005.160000

In [27]:
df.isnull().sum()

_id                                                  0
SlNo                                                 0
Station                                              0
Agency                                               0
State LGD Code                                       0
State                                                0
District LGD Code                                    0
District                                             0
Tehsil                                               0
Block                                                0
Village                                              0
River                                                0
Basin                                                0
Tributary                                            0
Subtributary                                         0
SubSubtributary                                      0
Local River                                          0
Latitude                                             0
Longitude                                            0
RL_MSL                                          236724
Data Acquisition Time                                0
Groundwater Level Telemetry 6 Hourly (meter)         0
dtype: int64

In [28]:
df.columns = df.columns.str.strip()

In [29]:
df['Groundwater Level Telemetry 6 Hourly (meter)'].describe()

count    336200.000000
mean         -5.636372
std          55.927805
min        -999.999000
25%         -16.071000
50%          -6.818000
75%          -1.344000
max        1005.160000
Name: Groundwater Level Telemetry 6 Hourly (meter), dtype: float64

In [30]:
df['Station'].nunique()

93

In [31]:
df['Station'].value_counts().head(20)

Station
Asafpur (UP-077)                      6307
Amgaon (UP-067)                       6298
Agra City (UP-017)                    6201
Airayan  (UP-023)                     6102
Badagaon (UP-049)                     5870
Bahjoi (UP-128)                       5859
Baba BelkharNath Dham (UP-045)        5839
Awagarh (UP-005)                      5818
Amauli (UP-027)                       5736
Aspur Deosara (UP-040)                5675
Badalpur (UP-091)                     5476
Bahuwa (UP-024)                       5004
Abhauli (UP-153)                      5002
Ahmadpur Savant (UP-163)              4997
Amroha Forest Department, Shallow     4825
Allahabad City (UP-046)               4817
Amroha Forest Department, Medium      4792
Aurai (UP-150)                        4719
Ashapur Dak Banglow-Malawan-Medium    4673
Amlour                                4484
Name: count, dtype: int64

In [32]:
df['Data Acquisition Time'] = py.to_datetime(df['Data Acquisition Time'])

/tmp/ipykernel_212436/2598825599.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Data Acquisition Time'] = py.to_datetime(df['Data Acquisition Time'])

In [33]:
level_col = "Groundwater Level Telemetry 6 Hourly (meter)"

df[level_col] = py.to_numeric(
    df[level_col],
    errors="coerce"
)

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.duplicated(
    subset=["Station", "Data Acquisition Time"]
).sum()

np.int64(0)

In [36]:
df = df.sort_values(
    ["Station", "Data Acquisition Time"]
).reset_index(drop=True)

In [37]:
df.head()

,_id,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,...,Basin,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,RL_MSL,Data Acquisition Time,Groundwater Level Telemetry 6 Hourly (meter)
0,1,1,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,2024-02-23 18:00:00,-0.247
1,2,2,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,2024-02-24 00:00:00,-0.256
2,3,3,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,2024-02-24 06:00:00,-0.252
3,4,4,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,2024-02-24 12:00:00,-0.167
4,5,5,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,2024-02-24 18:00:00,-0.256

In [38]:
df_path = '../data/processed/common.parquet'
df.to_parquet(
    df_path,
    index=False
)
print(f'Saved to {df_path}')

Saved to ../data/processed/common.parquet